Feat/StyleList
Childbutsmart/marseille-unite-speciale pull request #23
Opened 2024-03-26 16:26 UTC by Guillaume1804

pull request concernant la page de liste des criminels.
Intégration des fichiers json et des images en local afin d'éviter les problémes liés à l'accés à l'API.
Commencement de l'intégration du style avec MUI (nottement MUI Carousel).
Pour l'instant quelques soucis au niveau de l'affichage mais rien d'insurmontable

2024-03-26 18:42 UTC, Thesirix approved these changes
ok

2024-03-26 18:43 UTC, Thesirix approved these changes
ok

2024-03-26 18:43 UTC, Thesirix approved these changes
ok

2024-03-27 08:39 UTC, Childbutsmart requested changes
please, be careful before send PR.

2024-03-27 08:39 UTC, Emmanuelle-S requested changes
Attente que ça marche

2024-03-27 08:40 UTC, closed without merging